### ISSUE TITLE
Transaction Process for adding/updating/deleting information

### ISSUE THREAD

**Issue by Kentoseth** [musalbas/trustery#2]
Hi there.

I have been looking at implementing something similar to what you have built already, but seeing as you have already started building it, I thought I would attempt contributing here first.

Can you explain (as the title says), how the process of adding/deleting your PGP-key is done via the Ethereum-blockchain?

Are you using some type of token/key?

**Comment by musalbas** [comment]
Hi, sorry for the slow response, I forgot about issues for a while.

The process of adding a PGP key is doing by publishing the fingerprint of the key directly to the blockchain via the addAttribute smart contract method, and then publishing the key itself either on the blockchain too or on IPFS and linking to it on the blockchain. Keys can then be signed by any Ethereum address using the signAttribute method. Signatures of keys can be revoked ("deleted") by invoking the revokeSignature method in the smart contract.

What are you planning to implement/achieve?

Mustafa

**Comment by Kentoseth** [comment]
I was looking at a simplified (meaning it is straight-forward for end-users familiar with PGP) to add their keys.

I have evaluated Ethereum as an option, but I am also now looking at other block-chain options that are more suited to this type of public-facing storage.
